version: '3'

services:
  mongo:
    image: mongo
    hostname: mongo
    restart: always
    #environment:
    #  MONGO_INITDB_ROOT_USERNAME: root
    #  MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    networks:
      - stat

  statdevice:
    container_name: statdevice
    image: statdevice11
    ports:
      - 8081:8080
    networks:
      - stat
    links:
      - mongo
    depends_on:
      - mongo

networks:
  stat:

